### ISSUE TITLE
Feedback Desktop 08/04/2021

### ISSUE THREAD

**Issue by spersico** [SomosCodear/webconf-2021#1]
Antes que nada, ALTO LABURO, excelente ta quedando, la verdad. 

Voy a ir dejando todo por acá, algunos son nitpicks, el único que me jode la verdad es el de los bordes de los botones y checks. Manejen la prioridad como quieran.

**Contexto de pruebas**: Windows 10 - Pantalla 1080p de 23.5' - Firefox 86.0.1 - Edge 89 - Chrome 89

# Global (o se repite en varios steps)
- [ ] El :active state de botones y checks tienen un borde negro (el outline del browser) como en la imagen en Edge y Chrome, bien bien feo eso, rompe varios diseños al clickear y editar inputs:
![image](https://user-images.githubusercontent.com/10502605/113968234-120e8080-9809-11eb-9cc0-6051b76e4c7b.png)
![image](https://user-images.githubusercontent.com/10502605/113968575-bb557680-9809-11eb-995f-718b722196d3.png)
- [ ] Esto se repite: La barra indicadora de steps, de acuerdo al wireframe, debe mostrar una linea de donde estaban los steps anteriores:
![image](https://user-images.githubusercontent.com/10502605/113969228-fa37fc00-980a-11eb-8b06-886750117837.png)
- [x] El color del placeholder en FF se vé diferente a Edge y Chrome (prefiero el de Edge, el de FF me parece jodido de leer por el contraste):
![image](https://user-images.githubusercontent.com/10502605/113969049-a4635400-980a-11eb-8f99-2a9535f64abd.png)

# Primer Step
- [ ] El estado inicial del check del CFP en Edge y Chrome se vé como en la imágen (Si se resuelve el tema general de los bordes seleccionados, puede que esto sea irrelevante)
![image](https://user-images.githubusercontent.com/10502605/113967897-606f4f80-9808-11eb-82a4-cdec07866047.png)
En FF se vé un poco mejor:
![image](https://user-images.githubusercontent.com/10502605/113968035-a88e7200-9808-11eb-8f99-7d6572865da5.png)

# Segundo Step
- [x] El color del texto de los checks es diferente respecto al wireframe: 
![image](https://user-images.githubusercontent.com/10502605/113968834-459dda80-980a-11eb-97ca-6337741017e8.png)
- [ ] 5 caracteres mínimo para el titulo de una charla me parece re poco: 
![image](https://user-images.githubusercontent.com/10502605/113973261-6407d400-9812-11eb-9c58-c215e2e978d3.png)

# Tercer Step
- [x] Esto no estoy seguro si va o no. El logo de twitter no tiene alt text:
![image](https://user-images.githubusercontent.com/10502605/113969446-66b2fb00-980b-11eb-9f8e-e4e7ccf6e5e3.png)
- [ ] El minimo de caracteres del textarea me parece muy poco (le pondría unos 50 caracteres como mínimo).
- [x] En FF tengo una scrollbar en el tercer step, en los anteriores no tenía.
![image](https://user-images.githubusercontent.com/10502605/113969667-c6110b00-980b-11eb-9ac8-a5f54403bd9c.png)
- [x] En Edge y Chrome el dialog bubble que tiene flecha hacia abajo corta la bubble (en FF no pasa, y cuando tiene flecha lateral tampoco en ninguno) :
![image](https://user-images.githubusercontent.com/10502605/113969883-2dc75600-980c-11eb-90c8-1c62621cf1a3.png)
- [x] En todos los browsers le sacaría lo de resizable a la textarea, porque el coso para resizear rompe el borde redondeado: 
![image](https://user-images.githubusercontent.com/10502605/113970434-4126f100-980d-11eb-9171-ca1f444d21d6.png)
Y puede que hasta le pondría un límite de lineas de texto, porque el scroll me parece feo tambien, pero eso ya es cosa tuya.
- [ ] Validaciones palabras claves:
- Puedo poner tags repetidos (#spiderman #spiderman)
- puedo poner un tag de largo que yo quiera
- puedo poner infinitos tags
- puedo poner un solo tag
No me resulta intuitivo el texto del error "Seguí el formato", para mi hay que ser mas explícito. Pero tengo sueño y pocas ideas.

# Cuarto Step
- [x] Le sacaría el resizable al textaerea porque puedo romperlo 
![image](https://user-images.githubusercontent.com/10502605/113971052-62d4a800-980e-11eb-95bd-105b3d700185.png)
- [ ] El error es fancy... too fancy, pero no es lo suficientemente explicito, decime cuantas palabras/caracteres querés:
![image](https://user-images.githubusercontent.com/10502605/113971110-83046700-980e-11eb-8e67-400ca356af43.png)
Also, me di cuenta que el minimo para pasar son 10 caracteres. No se si es a proposito, pero me causa gracia que sea mas corto que el twit.
- [x] Los checkbox labels son de color negro (creo) y deberían ser del mismo color que el Input label (gris oscuro)
![image](https://user-images.githubusercontent.com/10502605/113971383-0d4ccb00-980f-11eb-8f8a-8c143c3e769a.png)
- [x] El disclaimer text del email se ve muy muy chiquito, a lo "me tuve que acercar a la pantalla para leerlo" chiquito. Y se ve diferente al wireframe. Captura de como se ve en FF en mi monitor 1920x1080p:
![image](https://user-images.githubusercontent.com/10502605/113971676-9bc14c80-980f-11eb-805a-d1fc47edfe8f.png)
Como en ese step hay ya como 
- [ ] Hay 7 tamaños diferente de letra en este step (contando los de error y el disclaimer). **Me triggereé**.
- [ ] Deberíamos dejarle poner solo un nombre? No vendría bien aunque sea poner en el placeholder un nombre y apellido (como hacemos con Ciudad, País.... also, consistencia entre inputs).

# After Submit screen
- [ ] Después de submitear, no me muestra nada, ni en Firefox, ni en edge, ni en chrome. En el figma había un mensaje y un boton.
![image](https://user-images.githubusercontent.com/10502605/113972224-ad572400-9810-11eb-8bf9-ce11abdf120a.png)

# Ideas:
- Estaría bueno que la imagen del costado sea un link para ir la página de webconf (que abra en una nueva pestaña, para que los que estén completando el form no pierdan lo llenado)
- Me gustó la animación del boton "continuar". Estaría bueno que el "Atrás" tuviese aunque sea un hover state.

**Comment by joelalejandro** [comment]
Por parte de diseño:

- Para los outlines voy a agregar una vista en Figma con cómo debería verse cada componente.
- En cuanto al error de minlength, podemos agregar así: `(al menos unos {minlength} caracteres)`. Supongo que el mínimo asumido de 10 es para escribir algo como "No hay detalles extra", pero estaría bueno desincentivar ese tipo de mensajes. Propongo que lo subamos a 200.
- El logo de Twitter va y es decorativo. La idea es que visualmente el pajarito está diciendo lo que dice el tweet. El logo **no debe** tener texto alternativo. Es más, recomiendo aplicarle `aria-hidden='true'` para que no aparezca.
- En Figma cuento estos tamaños:
  - Título del step: 40px
  - Labels para textbox y checkbox: 24px
  - Contenido de inputs: 32px
  - Disclaimer: 16px
- Deberíamos dejarle poner solo un nombre. Este formulario pretende ser lo menos restrictivo posible. En el caso de que la persona queda seleccionada, se le hace un pedido de datos un poco más exhaustivo, pero para empezar, no nos es requerido tener el apellido.

**Comment by asermax** [comment]
Desde desarrollo:
- Algunos detalles los voy arreglando, los voy a ir marcando acá a medida que los arregle.
- La pantalla blanca al final fué por un error de la API por una cuestión de configuración, eso quedó arrglado. No se si queremos agregar una pantalla de error para dejar al menos un mailto en caso que le salte un issue a alguno.
- Quedo a la espera de los diseños para el outline.
- Con respecto al texto de las validaciones, min length, etc no tengo ninguna opinión concreta, así que los dejo que discutan, decidan y lo agregamos. De última @spersico hacete una PR con los cambios puntuales que quieras hacer de eso y se discute ahí, me parece que va a ser más fácil.
- La validación del field de hashtags no me parece muy relevante la verdad, lo único que nos interesa es que nos pongan una lista de hashtags para darnos una idea de la charla, no se van a usar de manera automática ni nada por el estilo por lo que no afecta si están duplicados, tenes uno o un millón.
- Respecto a placeholders, en el diseño había algunos que me parecía que tenían sentido y otros que no, por eso hay algunos nomás. Propongo lo mismo que en el caso de las validaciones.
- Lo del link del logo lo hago, me parece bien para mantener la navegabilidad de la página también siendo que desde la landing tenemos un link al CFP.
- Lo de la animación de los botones no te sabría bien que hacer con la variante blanca; el primary y secondary tienen ese doble outline que me copó para meterle esa animación onda 3D pero con el otro no está esa posibilidad así que no se me ocurre nada.
